export default [
  {
    id: 'ins-001',
    name: 'Aphid',
    scientific_name: 'Aphis gossypii',
    local_names: { bangla: 'মাছি পোকা', chatgaiya: 'মাছিয়া', english: 'Aphid' },
    type: 'sucking',
    description: 'ছোট কালো/সবুজ পোকা পাতার নিচে বসে, দ্রুত বংশবিস্তার করে',
    damage: 'রস চুষে খায়, পাতা কুঁকড়ে যায়, মধুর আস্বেক তৈরি হয়, ভাইরাস ছড়ায়',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'শসা', 'ক্যাপসিকাম', 'ফুলকপি'],
    season: 'সর্বকালীন, বেশি শীতে',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'সাবান পানি স্প্রে', 'লেডিবার্ড ছেড়ে দিন', 'নীল স্টিকি ট্র্যাপ'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'ইমিডাক্লোপ্রিড ০.৫ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'অতিরিক্ত নাইট্রোজেন এড়িয়ে চলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-002',
    name: 'Whitefly',
    scientific_name: 'Bemisia tabaci',
    local_names: { bangla: 'সাদা মাছি', chatgaiya: 'সাদা মাছিয়া', english: 'Whitefly' },
    type: 'sucking',
    description: 'ছোট সাদা পোকা পাতার নিচে বসে, উড়ে বেড়ায়',
    damage: 'রস চুষে খায়, মধুর আস্বেক তৈরি হয়, ভাইরাস ছড়ায়, পাতা হলুদ হয়',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'শসা', 'ক্যাপসিকাম'],
    season: 'সর্বকালীন, বেশি গরমে',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'হলুদ স্টিকি ট্র্যাপ', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'থায়ামেথোক্সাম ০.৩ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'অতিরিক্ত নাইট্রোজেন এড়িয়ে চলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-003',
    name: 'Thrips',
    scientific_name: 'Thrips tabaci',
    local_names: { bangla: 'থ্রিপস', chatgaiya: 'ছোট পোকা', english: 'Thrips' },
    type: 'sucking',
    description: 'অতি ছোট লম্বা পোকা, পাতার নিচে বসে',
    damage: 'রস চুষে খায়, পাতা রূপালি হয়, ফুল ও ফলের মান নষ্ট করে',
    affected_crops: ['পেঁপে', 'কলা', 'মরিচ', 'টমেটো', 'সবজি'],
    season: 'সর্বকালীন, বেশি শুষ্ক',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'নীল স্টিকি ট্র্যাপ', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'স্পাইনোসাড ০.৫ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'পানি স্প্রে করুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-004',
    name: 'Fruit Borer',
    scientific_name: 'Helicoverpa armigera',
    local_names: { bangla: 'ফল পোকা', chatgaiya: 'ফল পোকা', english: 'Fruit Borer' },
    type: 'chewing',
    description: 'সবুজ/বাদামি পোকা ফলের ভিতরে ঢুকে খায়',
    damage: 'ফলের ভিতরে ছিদ্র তৈরি করে, ফল নষ্ট করে, দামি ফসলের ক্ষতি করে',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'ভুট্টা', 'কাঁচালোবিচিতে'],
    season: 'গ্রীষ্মকালীন',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'ফেরোমোন ট্র্যাপ', 'বি.টি. স্প্রে ৫ গ্রাম/লিটার'],
    chemical_control: ['কারবারিল ১ মিলি/লিটার', 'ফিপ্রোনিল ০.৫ মিলি/লিটার', 'এমামেক্টিন বেনজোয়েট ০.৪ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'আক্রান্ত ফল সংগ্রহ ও ধ্বংস', 'ফেরোমোন ট্র্যাপ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-005',
    name: 'Leaf Miner',
    scientific_name: 'Liriomyza sativae',
    local_names: { bangla: 'পাতা খোঁড়া পোকা', chatgaiya: 'পাতা খোঁড়া', english: 'Leaf Miner' },
    type: 'mining',
    description: 'ছোট সাদা লার্ভা পাতার ভিতরে খোঁড়া তৈরি করে',
    damage: 'পাতায় সাদা রেখা তৈরি করে, পাতা নষ্ট করে, ফটোসিন্থেসিস কমায়',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'শসা', 'সালাদ'],
    season: 'সর্বকালীন',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'হলুদ স্টিকি ট্র্যাপ', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'অ্যাবামেক্টিন ০.৫ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'আক্রান্ত পাতা ছিঁড়ে ফেলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-006',
    name: 'Spider Mite',
    scientific_name: 'Tetranychus urticae',
    local_names: { bangla: 'মাকড়সা পোকা', chatgaiya: 'মাকড়সা', english: 'Spider Mite' },
    type: 'sucking',
    description: 'অতি ছোট লাল/হলুদ পোকা, পাতার নিচে সুতা বেঁধে থাকে',
    damage: 'রস চুষে খায়, পাতা হলুদ হয়, সুতা তৈরি হয়, গাছ শুকিয়ে যায়',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'শসা', 'কলা'],
    season: 'শুষ্ক মৌসুম',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'পানি স্প্রে', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'অ্যাবামেক্টিন ০.৫ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'পানি স্প্রে করুন', 'আর্দ্রতা বজায় রাখুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-007',
    name: 'Jassid',
    scientific_name: 'Amrasca biguttula',
    local_names: { bangla: 'জাসিড', chatgaiya: 'পাতা পোকা', english: 'Jassid' },
    type: 'sucking',
    description: 'ছোট সবুজ পোকা পাতার নিচে বসে',
    damage: 'রস চুষে খায়, পাতার প্রান্ত কুঁকড়ে যায়, হলুদ হয়',
    affected_crops: ['বাগান', 'কপি', 'শসা', 'মরিচ', 'বেগুন'],
    season: 'সর্বকালীন',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'সাবান পানি স্প্রে', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'থায়ামেথোক্সাম ০.৩ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'অতিরিক্ত নাইট্রোজেন এড়িয়ে চলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-008',
    name: 'Mealybug',
    scientific_name: 'Phenacoccus solenopsis',
    local_names: { bangla: 'মিলিবাগ', chatgaiya: 'সাদা পোকা', english: 'Mealybug' },
    type: 'sucking',
    description: 'সাদা, তুলতুলে পোকা, গুচ্ছে বসে',
    damage: 'রস চুষে খায়, মধুর আস্বেক তৈরি হয়, গাছ দুর্বল হয়',
    affected_crops: ['কলা', 'আম', 'পেঁপে', 'সবজি', 'ফুল'],
    season: 'সর্বকালীন, বেশি গরমে',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'সাবান পানি স্প্রে', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'থায়ামেথোক্সাম ০.৩ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'আক্রান্ত অংশ কেটে ফেলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-009',
    name: 'Stem Borer',
    scientific_name: 'Chilo suppressalis',
    local_names: { bangla: 'কান্ড পোকা', chatgaiya: 'কান্ড পোকা', english: 'Stem Borer' },
    type: 'chewing',
    description: 'সাদা/বাদামি লার্ভা কান্ডের ভিতরে ঢুকে খায়',
    damage: 'কান্ডের ভিতরে খোঁড়া তৈরি করে, গাছ শুকিয়ে যায়, ফল কমে',
    affected_crops: ['ধান', 'গম', 'ভুট্টা', 'আখ'],
    season: 'বর্ষাকালীন',
    organic_control: ['বি.টি. স্প্রে ৫ গ্রাম/লিটার', 'ফেরোমোন ট্র্যাপ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস'],
    chemical_control: ['কারবারিল ১ মিলি/লিটার', 'ফিপ্রোনিল ০.৫ মিলি/লিটার', 'এমামেক্টিন বেনজোয়েট ০.৪ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস', 'ফেরোমোন ট্র্যাপ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-010',
    name: 'Caterpillar',
    scientific_name: 'Spodoptera litura',
    local_names: { bangla: 'ইলিশা পোকা', chatgaiya: 'পোকা', english: 'Tobacco Caterpillar' },
    type: 'chewing',
    description: 'বড় সবুজ/বাদামি পোকা, রাতে বেশি খায়',
    damage: 'পাতা ও কান্ড খেয়ে ফেলে, গাছ নষ্ট করে',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'ভুট্টা', 'সুজি'],
    season: 'গ্রীষ্মকালীন',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'বি.টি. স্প্রে ৫ গ্রাম/লিটার', 'ফেরোমোন ট্র্যাপ'],
    chemical_control: ['কারবারিল ১ মিলি/লিটার', 'ফিপ্রোনিল ০.৫ মিলি/লিটার', 'এমামেক্টিন বেনজোয়েট ০.৪ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস', 'ফেরোমোন ট্র্যাপ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'ins-011',
    name: 'Diamond Back Moth',
    scientific_name: 'Plutella xylostella',
    local_names: { bangla: 'কপি পোকা', chatgaiya: 'কপি পোকা', english: 'Diamond Back Moth' },
    type: 'chewing',
    description: 'ছোট সবুজ লার্ভা পাতা খায়',
    damage: 'পাতা খেয়ে ফেলে, কপির মান নষ্ট করে',
    affected_crops: ['কপি', 'ফুলকপি', 'বাঁধাকপি', 'মূলা'],
    season: 'শীতকালীন',
    organic_control: ['বি.টি. স্প্রে ৫ গ্রাম/লিটার', 'নিম তেল ৫ মিলি/লিটার', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['কারবারিল ১ মিলি/লিটার', 'ফিপ্রোনিল ০.৫ মিলি/লিটার', 'এমামেক্টিন বেনজোয়েট ০.৪ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'আক্রান্ত পাতা ছিঁড়ে ফেলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  }
];