module.exports = [
  {
    id: 'fungal-001',
    name: 'Late Blight',
    scientific_name: 'Phytophthora infestans',
    local_names: { bangla: 'লেট ব্লাইট', chatgaiya: 'লেট ব্লাইট', english: 'Late Blight' },
    type: 'fungal',
    symptoms: {
      early: 'পাতায় ছোট হলুদ-সবুজ দাগ',
      late: 'পাতা কালো-বাদামি হয়ে পড়ে, কাণ্ড পচে',
      description: 'বৃষ্টির মৌসুমে দ্রুত ছড়ায়'
    },
    cause: 'Phytophthora infestans ছত্রাক',
    spread: 'বাতাস, পানি, সংক্রমিত বীজ',
    weather: { temperature: '১৫-২৫°C', humidity: '৯০%+', rainfall: 'বেশি বৃষ্টি' },
    affected_crops: ['টমেটো', 'আলু'],
    organic_control: ['ট্রাইকোডার্মা ৫ গ্রাম/লিটার', 'নিম তেল ৫ মিলি/লিটার', 'বীজ শোধন'],
    chemical_control: ['ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার', 'কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার', 'মেটালাক্সিল ০.৫ গ্রাম/লিটার'],
    prevention: ['লেট ব্লাইট প্রতিরোধী জাত ব্যবহার', 'ভালো জল নিষ্কাশন', 'ফসল আবর্তন'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'fungal-002',
    name: 'Early Blight',
    scientific_name: 'Alternaria solani',
    local_names: { bangla: 'আর্লি ব্লাইট', chatgaiya: 'আর্লি ব্লাইট', english: 'Early Blight' },
    type: 'fungal',
    symptoms: {
      early: 'পাতায় বৃত্তাকার বাদামি দাগ',
      late: 'দাগ বড় হয়, পাতা হলুদ হয়ে ঝরে যায়',
      description: 'নিম্ন পাতা থেকে শুরু হয়'
    },
    cause: 'Alternaria solani ছত্রাক',
    spread: 'বাতাস, পানি, মাটির অবশেষ',
    weather: { temperature: '২৫-৩০°C', humidity: '৮০%+', rainfall: 'মাঝারি বৃষ্টি' },
    affected_crops: ['টমেটো', 'আলু', 'বেগুন'],
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'বেকিং সোডা ৫ গ্রাম/লিটার', 'ট্রাইকোডার্মা'],
    chemical_control: ['ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার', 'কপার হাইড্রক্সাইড ২ গ্রাম/লিটার', 'ক্লোরোথালোনিল ২ মিলি/লিটার'],
    prevention: ['ফসল আবর্তন', 'আক্রান্ত অংশ পোড়ানো', 'পর্যাপ্ত পুষ্টি বজায়'],
    severity: 'medium',
    season: 'গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'fungal-003',
    name: 'Powdery Mildew',
    scientific_name: 'Erysiphe cichoracearum',
    local_names: { bangla: 'পাউডারি মিলডিউ', chatgaiya: 'পাউডারি মিলডিউ', english: 'Powdery Mildew' },
    type: 'fungal',
    symptoms: {
      early: 'পাতায় সাদা পাউডার জমা',
      late: 'পাতা কুঁকড়ে যায়, ফসল কমে',
      description: 'শুষ্ক আবহাওয়ায় বেশি হয়'
    },
    cause: 'Erysiphe cichoracearum ছত্রাক',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '২০-৩০°C', humidity: '৫০-৭০%', rainfall: 'কম বৃষ্টি' },
    affected_crops: ['শসা', 'কুমড়া', 'লাউ'],
    organic_control: ['সালফার ২ গ্রাম/লিটার', 'দুধ ১:১০ অনুপাতে', 'নিম তেল'],
    chemical_control: ['সালফার ২ গ্রাম/লিটার', 'কারবোক্সিন ১ গ্রাম/লিটার', 'প্রোপিকোনাজল ০.৫ মিলি/লিটার'],
    prevention: ['ভালো বাতাস চলাচল', 'পাতায় পানি না লাগান', 'সুস্থ জাত ব্যবহার'],
    severity: 'medium',
    season: 'শীত',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'fungal-004',
    name: 'Downy Mildew',
    scientific_name: 'Pseudoperonospora cubensis',
    local_names: { bangla: 'ডাউনি মিলডিউ', chatgaiya: 'ডাউনি মিলডিউ', english: 'Downy Mildew' },
    type: 'fungal',
    symptoms: {
      early: 'পাতার উপরে হলুদ দাগ',
      late: 'নিচে ধূসর আস্তরণ, পাতা ঝরে যায়',
      description: 'বর্ষায় দ্রুত ছড়ায়'
    },
    cause: 'Pseudoperonospora cubensis ছত্রাক',
    spread: 'বাতাস, পানি',
    weather: { temperature: '১৫-২৫°C', humidity: '৯০%+', rainfall: 'বেশি বৃষ্টি' },
    affected_crops: ['শসা', 'কুমড়া', 'আলু'],
    organic_control: ['ট্রাইকোডার্মা ৫ গ্রাম/লিটার', 'নিম তেল ৫ মিলি/লিটার', 'পানি লাগানো বন্ধ'],
    chemical_control: ['ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার', 'মেটালাক্সিল ০.৫ গ্রাম/লিটার', 'কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার'],
    prevention: ['ভালো জল নিষ্কাশন', 'বীজ শোধন', 'ফসল আবর্তন'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'fungal-005',
    name: 'Rust',
    scientific_name: 'Puccinia species',
    local_names: { bangla: 'রাস্ট', chatgaiya: 'রাস্ট', english: 'Rust' },
    type: 'fungal',
    symptoms: {
      early: 'পাতায় কমলা-বাদামি ফোঁড়া',
      late: 'ফোঁড়া ফেটে পাউড়া ছড়ায়, পাতা ঝরে যায়',
      description: 'বর্ষা ও শীতে বেশি হয়'
    },
    cause: 'Puccinia species ছত্রাক',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '১৫-২৫°C', humidity: '৮০%+', rainfall: 'মাঝারি বৃষ্টি' },
    affected_crops: ['ডালিম', 'বাঁধাকপি', 'পেঁয়াজ'],
    organic_control: ['সালফার ২ গ্রাম/লিটার', 'নিম তেল', 'আক্রান্ত অংশ পোড়ানো'],
    chemical_control: ['প্রোপিকোনাজল ০.৫ মিলি/লিটার', 'ট্রাইঅ্যাডিমেফন ০.৬ গ্রাম/লিটার', 'কারবোক্সিন ১ গ্রাম/লিটার'],
    prevention: ['রাস্ট প্রতিরোধী জাত', 'ভালো জল নিষ্কাশন', 'আক্রান্ত অংশ পোড়ানো'],
    severity: 'medium',
    season: 'বর্ষা-শীত',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'fungal-006',
    name: 'Leaf Spot',
    scientific_name: 'Cercospora leaf spot',
    local_names: { bangla: 'পাতা দাগ', chatgaiya: 'পাতা দাগ', english: 'Leaf Spot' },
    type: 'fungal',
    symptoms: {
      early: 'পাতায় ছোট বৃত্তাকার দাগ',
      late: 'দাগ বড় হয়, পাতা হলুদ হয়ে ঝরে যায়',
      description: 'বর্ষায় বেশি হয়'
    },
    cause: 'Cercospora species ছত্রাক',
    spread: 'বাতাস, পানি, মাটি',
    weather: { temperature: '২৫-৩০°C', humidity: '৮০%+', rainfall: 'বেশি বৃষ্টি' },
    affected_crops: ['পেঁয়াজ', 'লেবু', 'আম'],
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'বেকিং সোডা ৫ গ্রাম/লিটার', 'ট্রাইকোডার্মা'],
    chemical_control: ['ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার', 'কপার হাইড্রক্সাইড ২ গ্রাম/লিটার', 'ক্লোরোথালোনিল ২ মিলি/লিটার'],
    prevention: ['ফসল আবর্তন', 'আক্রান্ত অংশ পোড়ানো', 'ভালো জল নিষ্কাশন'],
    severity: 'medium',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'fungal-007',
    name: 'Root Rot',
    scientific_name: 'Fusarium solani',
    local_names: { bangla: 'মূল পচা', chatgaiya: 'মূল পচা', english: 'Root Rot' },
    type: 'fungal',
    symptoms: {
      early: 'গাছ লালচে হয়ে যায়',
      late: 'মূল পচে যায়, গাছ মরে যায়',
      description: 'অতিরিক্ত পানিতে বেশি হয়'
    },
    cause: 'Fusarium solani ছত্রাক',
    spread: 'মাটি, পানি, সংক্রমিত বীজ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৮০%+', rainfall: 'বেশি পানি' },
    affected_crops: ['মটরশুটি', 'সয়াবিন', 'কমলা'],
    organic_control: ['ট্রাইকোডার্মা ১০ গ্রাম/কেজি মাটি', 'বীজ শোধন', 'ভালো জল নিষ্কাশন'],
    chemical_control: ['কারবোক্সিন ২ গ্রাম/লিটার', 'ট্রাইঅ্যাডিমেফন ০.৬ গ্রাম/লিটার', 'ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার'],
    prevention: ['ভালো জল নিষ্কাশন', 'ফসল আবর্তন', 'সুস্থ বীজ ব্যবহার'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'fungal-008',
    name: 'Wilt',
    scientific_name: 'Fusarium oxysporum',
    local_names: { bangla: 'ম্লানি', chatgaiya: 'ম্লানি', english: 'Wilt' },
    type: 'fungal',
    symptoms: {
      early: 'গাছের একপাশে পাতা ঝরে যায়',
      late: 'পুরো গাছ ম্লান হয়ে মরে যায়',
      description: 'মাটির ছত্রাক থেকে ছড়ায়'
    },
    cause: 'Fusarium oxysporum ছত্রাক',
    spread: 'মাটি, পানি, সংক্রমিত বীজ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৭০%+', rainfall: 'মাঝারি বৃষ্টি' },
    affected_crops: ['মরিচ', 'টমেটো', 'আলু'],
    organic_control: ['ট্রাইকোডার্মা ১০ গ্রাম/কেজি মাটি', 'বীজ শোধন', 'ফসল আবর্তন'],
    chemical_control: ['কারবোক্সিন ২ গ্রাম/লিটার', 'ট্রাইঅ্যাডিমেফন ০.৬ গ্রাম/লিটার', 'ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার'],
    prevention: ['ম্লানি প্রতিরোধী জাত ব্যবহার', 'ফসল আবর্তন', 'ভালো জল নিষ্কাশন'],
    severity: 'high',
    season: 'গ্রীষ্ম-বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  }
];
