export default [
  {
    id: 'viral-001',
    name: 'Mosaic Virus',
    scientific_name: 'Tobacco Mosaic Virus (TMV)',
    local_names: { bangla: 'মোজাইক ভাইরাস', chatgaiya: 'মোজাইক ভাইরাস', english: 'Mosaic Virus' },
    type: 'viral',
    symptoms: {
      early: 'পাতায় সবুজ ও হলুদ মোজাইক প্যাটার্ন',
      late: 'পাতা কুঁকড়ে যায়, গাছ ধীরে বৃদ্ধি পায়',
      description: 'শুষ্ক মৌসুমে বেশি ছড়ায়'
    },
    cause: 'Tobacco Mosaic Virus (TMV)',
    spread: 'স্পর্শ, সরঞ্জাম, পোকা',
    weather: { temperature: '২০-৩০°C', humidity: '৬০-৮০%', rainfall: 'মাঝারি' },
    affected_crops: ['মরিচ', 'টমেটো', 'তামাক'],
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'পোকা নিয়ন্ত্রণ', 'সংক্রমিত গাছ সরিয়ে ফেলা'],
    chemical_control: ['নিম তেল ৫ মিলি/লিটার', 'পাইরিথ্রিন ১ মিলি/লিটার', 'দাইমিথোয়েট ০.৫ মিলি/লিটার'],
    prevention: ['সুস্থ বীজ ব্যবহার', 'পোকা নিয়ন্ত্রণ', 'হাত ধুয়ে কাজ করা'],
    severity: 'high',
    season: 'সর্বকালীন',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'viral-002',
    name: 'Leaf Curl',
    scientific_name: 'Tomato Leaf Curl Virus (ToLCV)',
    local_names: { bangla: 'পাতা কুঁকড়ানো', chatgaiya: 'পাতা কুঁকড়ানো', english: 'Leaf Curl' },
    type: 'viral',
    symptoms: {
      early: 'পাতা উপরের দিকে কুঁকড়ে যায়',
      late: 'পাতা ছোট হয়ে যায়, গাছ বৃদ্ধি পায় না',
      description: 'হোয়াইটফ্লাই ছড়ায়'
    },
    cause: 'Tomato Leaf Curl Virus (ToLCV)',
    spread: 'হোয়াইটফ্লাই',
    weather: { temperature: '২৫-৩৫°C', humidity: '৬০-৮০%', rainfall: 'কম' },
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন'],
    organic_control: ['হোয়াইটফ্লাই নিয়ন্ত্রণ', 'নিম তেল ৫ মিলি/লিটার', 'সংক্রমিত গাছ সরিয়ে ফেলা'],
    chemical_control: ['দাইমিথোয়েট ০.৫ মিলি/লিটার', 'ইমিডাক্লোপ্রিড ০.৩ মিলি/লিটার', 'নিম তেল ৫ মিলি/লিটার'],
    prevention: ['হোয়াইটফ্লাই নিয়ন্ত্রণ', 'লেট কার্ল প্রতিরোধী জাত', 'ইয়েলো স্টিকি ট্র্যাপ'],
    severity: 'high',
    season: 'গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'viral-003',
    name: 'Yellow Vein Mosaic',
    scientific_name: 'Bhendi Yellow Vein Mosaic Virus (BYVMV)',
    local_names: { bangla: 'ইয়েলো ভেইন মোজাইক', chatgaiya: 'ইয়েলো ভেইন মোজাইক', english: 'Yellow Vein Mosaic' },
    type: 'viral',
    symptoms: {
      early: 'পাতার শিরায় হলুদ রঙ',
      late: 'পাতা সম্পূর্ণ হলুদ হয়ে যায়',
      description: 'হোয়াইটফ্লাই ছড়ায়'
    },
    cause: 'Bhendi Yellow Vein Mosaic Virus (BYVMV)',
    spread: 'হোয়াইটফ্লাই',
    weather: { temperature: '২৫-৩৫°C', humidity: '৬০-৮০%', rainfall: 'কম' },
    affected_crops: ['ঢেঁড়স'],
    organic_control: ['হোয়াইটফ্লাই নিয়ন্ত্রণ', 'নিম তেল ৫ মিলি/লিটার', 'সংক্রমিত গাছ সরিয়ে ফেলা'],
    chemical_control: ['দাইমিথোয়েট ০.৫ মিলি/লিটার', 'ইমিডাক্লোপ্রিড ০.৩ মিলি/লিটার', 'নিম তেল ৫ মিলি/লিটার'],
    prevention: ['হোয়াইটফ্লাই নিয়ন্ত্রণ', 'প্রতিরোধী জাত ব্যবহার', 'ইয়েলো স্টিকি ট্র্যাপ'],
    severity: 'high',
    season: 'গ্রীষ্ম-বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'viral-004',
    name: 'Tomato Yellow Leaf Curl',
    scientific_name: 'Tomato Yellow Leaf Curl Virus (TYLCV)',
    local_names: { bangla: 'টমেটো ইয়েলো লিফ কার্ল', chatgaiya: 'টমেটো ইয়েলো লিফ কার্ল', english: 'Tomato Yellow Leaf Curl' },
    type: 'viral',
    symptoms: {
      early: 'পাতা হলুদ ও কুঁকড়ে যায়',
      late: 'গাছ ধীরে বৃদ্ধি পায়, ফসল কমে',
      description: 'হোয়াইটফ্লাই ছড়ায়'
    },
    cause: 'Tomato Yellow Leaf Curl Virus (TYLCV)',
    spread: 'হোয়াইটফ্লাই',
    weather: { temperature: '২৫-৩৫°C', humidity: '৬০-৮০%', rainfall: 'কম' },
    affected_crops: ['টমেটো'],
    organic_control: ['হোয়াইটফ্লাই নিয়ন্ত্রণ', 'নিম তেল ৫ মিলি/লিটার', 'সংক্রমিত গাছ সরিয়ে ফেলা'],
    chemical_control: ['দাইমিথোয়েট ০.৫ মিলি/লিটার', 'ইমিডাক্লোপ্রিড ০.৩ মিলি/লিটার', 'নিম তেল ৫ মিলি/লিটার'],
    prevention: ['হোয়াইটফ্লাই নিয়ন্ত্রণ', 'TYLCV প্রতিরোধী জাত', 'ইয়েলো স্টিকি ট্র্যাপ'],
    severity: 'high',
    season: 'গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'viral-005',
    name: 'Cucumber Mosaic',
    scientific_name: 'Cucumber Mosaic Virus (CMV)',
    local_names: { bangla: 'কুমড়ার মোজাইক', chatgaiya: 'কুমড়ার মোজাইক', english: 'Cucumber Mosaic' },
    type: 'viral',
    symptoms: {
      early: 'পাতায় সবুজ ও হলুদ মোজাইক',
      late: 'পাতা কুঁকড়ে যায়, ফসল কমে',
      description: 'পোকা ছড়ায়'
    },
    cause: 'Cucumber Mosaic Virus (CMV)',
    spread: 'পোকা, স্পর্শ',
    weather: { temperature: '২০-৩০°C', humidity: '৬০-৮০%', rainfall: 'মাঝারি' },
    affected_crops: ['শসা', 'কুমড়া', 'লাউ'],
    organic_control: ['পোকা নিয়ন্ত্রণ', 'নিম তেল ৫ মিলি/লিটার', 'সংক্রমিত গাছ সরিয়ে ফেলা'],
    chemical_control: ['নিম তেল ৫ মিলি/লিটার', 'পাইরিথ্রিন ১ মিলি/লিটার', 'দাইমিথোয়েট ০.৫ মিলি/লিটার'],
    prevention: ['পোকা নিয়ন্ত্রণ', 'সুস্থ বীজ ব্যবহার', 'ফসল আবর্তন'],
    severity: 'medium',
    season: 'সর্বকালীন',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'viral-006',
    name: 'Rice Tungro',
    scientific_name: 'Rice Tungro Bacilliform Virus (RTBV)',
    local_names: { bangla: 'ধানের টাঙ্গরো', chatgaiya: 'ধানের টাঙ্গরো', english: 'Rice Tungro' },
    type: 'viral',
    symptoms: {
      early: 'পাতা হলুদ হয়ে যায়',
      late: 'গাছ ধীরে বৃদ্ধি পায়, ফসল কমে',
      description: 'পাটাটাই ছড়ায়'
    },
    cause: 'Rice Tungro Bacilliform Virus (RTBV)',
    spread: 'পাটাটাই',
    weather: { temperature: '২৫-৩০°C', humidity: '৮০%+', rainfall: 'বেশি' },
    affected_crops: ['ধান'],
    organic_control: ['পাটাটাই নিয়ন্ত্রণ', 'নিম তেল ৫ মিলি/লিটার', 'সংক্রমিত গাছ সরিয়ে ফেলা'],
    chemical_control: ['দাইমিথোয়েট ০.৫ মিলি/লিটার', 'মালাথিয়ন ২ মিলি/লিটার', 'নিম তেল ৫ মিলি/লিটার'],
    prevention: ['পাটাটাই নিয়ন্ত্রণ', 'টাঙ্গরো প্রতিরোধী জাত', 'ফসল আবর্তন'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  }
];
