export default [
  {
    id: 'bacterial-001',
    name: 'Bacterial Spot',
    scientific_name: 'Xanthomonas campestris',
    local_names: { bangla: 'ব্যাকটেরিয়াল স্পট', chatgaiya: 'ব্যাকটেরিয়াল স্পট', english: 'Bacterial Spot' },
    type: 'bacterial',
    symptoms: {
      early: 'পাতায় ছোট কালো দাগ',
      late: 'দাগ বড় হয়, পাতা ঝরে যায়',
      description: 'বর্ষায় দ্রুত ছড়ায়'
    },
    cause: 'Xanthomonas campestris ব্যাকটেরিয়া',
    spread: 'পানি, বীজ, সরঞ্জাম',
    weather: { temperature: '২৫-৩০°C', humidity: '৮০%+', rainfall: 'বেশি বৃষ্টি' },
    affected_crops: ['মরিচ', 'টমেটো', 'আলু'],
    organic_control: ['বীজ শোধন', 'নিম তেল ৫ মিলি/লিটার', 'ট্রাইকোডার্মা'],
    chemical_control: ['কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার', 'স্ট্রেপটোমাইসিন ০.৫ গ্রাম/লিটার', 'ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার'],
    prevention: ['বীজ শোধন', 'ভালো জল নিষ্কাশন', 'ফসল আবর্তন'],
    severity: 'medium',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'bacterial-002',
    name: 'Bacterial Wilt',
    scientific_name: 'Ralstonia solanacearum',
    local_names: { bangla: 'ব্যাকটেরিয়াল ম্লানি', chatgaiya: 'ব্যাকটেরিয়াল ম্লানি', english: 'Bacterial Wilt' },
    type: 'bacterial',
    symptoms: {
      early: 'গাছ একদিন রাতে ম্লান হয়',
      late: 'গাছ সবুজ থাকতে থাকতে মরে যায়',
      description: 'মাটির ব্যাকটেরিয়া থেকে ছড়ায়'
    },
    cause: 'Ralstonia solanacearum ব্যাকটেরিয়া',
    spread: 'মাটি, পানি, সংক্রমিত বীজ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৮০%+', rainfall: 'বেশি পানি' },
    affected_crops: ['আলু', 'টমেটো', 'মরিচ'],
    organic_control: ['বীজ শোধন', 'ট্রাইকোডার্মা ১০ গ্রাম/কেজি মাটি', 'ফসল আবর্তন'],
    chemical_control: ['স্ট্রেপটোমাইসিন ০.৫ গ্রাম/লিটার', 'কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার', 'কারবোক্সিন ২ গ্রাম/লিটার'],
    prevention: ['ভালো জল নিষ্কাশন', 'ফসল আবর্তন', 'ম্লানি প্রতিরোধী জাত'],
    severity: 'high',
    season: 'বর্ষা-গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'bacterial-003',
    name: 'Bacterial Leaf Blight',
    scientific_name: 'Xanthomonas oryzae',
    local_names: { bangla: 'ব্যাকটেরিয়াল লিফ ব্লাইট', chatgaiya: 'ব্যাকটেরিয়াল লিফ ব্লাইট', english: 'Bacterial Leaf Blight' },
    type: 'bacterial',
    symptoms: {
      early: 'পাতার ধারে হলুদ দাগ',
      late: 'পাতা শুকিয়ে যায়, ফসল কমে',
      description: 'ধানে বেশি হয়'
    },
    cause: 'Xanthomonas oryzae ব্যাকটেরিয়া',
    spread: 'পানি, বীজ, সরঞ্জাম',
    weather: { temperature: '২৫-৩৫°C', humidity: '৮০%+', rainfall: 'বেশি বৃষ্টি' },
    affected_crops: ['ধান'],
    organic_control: ['বীজ শোধন', 'নিম তেল ৫ মিলি/লিটার', 'ট্রাইকোডার্মা'],
    chemical_control: ['স্ট্রেপটোমাইসিন ০.৫ গ্রাম/লিটার', 'কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার', 'ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার'],
    prevention: ['বীজ শোধন', 'ভালো জল নিষ্কাশন', 'ফসল আবর্তন'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'bacterial-004',
    name: 'Soft Rot',
    scientific_name: 'Erwinia carotovora',
    local_names: { bangla: 'মৃদু পচা', chatgaiya: 'মৃদু পচা', english: 'Soft Rot' },
    type: 'bacterial',
    symptoms: {
      early: 'গাছের নিচে পানি ভেজা দাগ',
      late: 'কাণ্ড ও মূল পচে যায়, দুর্গন্ধ তৈরি হয়',
      description: 'অতিরিক্ত পানিতে বেশি হয়'
    },
    cause: 'Erwinia carotovora ব্যাকটেরিয়া',
    spread: 'মাটি, পানি, সংক্রমিত বীজ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৮০%+', rainfall: 'বেশি পানি' },
    affected_crops: ['পেঁয়াজ', 'আলু', 'গাজর'],
    organic_control: ['ভালো জল নিষ্কাশন', 'বীজ শোধন', 'ট্রাইকোডার্মা'],
    chemical_control: ['কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার', 'স্ট্রেপটোমাইসিন ০.৫ গ্রাম/লিটার', 'ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার'],
    prevention: ['ভালো জল নিষ্কাশন', 'ফসল আবর্তন', 'সংক্রমিত অংশ পোড়ানো'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'bacterial-005',
    name: 'Bacterial Canker',
    scientific_name: 'Pseudomonas syringae',
    local_names: { bangla: 'ব্যাকটেরিয়াল ক্যানকার', chatgaiya: 'ব্যাকটেরিয়াল ক্যানকার', english: 'Bacterial Canker' },
    type: 'bacterial',
    symptoms: {
      early: 'কাণ্ডে ছোট কালো দাগ',
      late: 'দাগ বড় হয়, কাণ্ড ফেটে যায়',
      description: 'শীতে বেশি হয়'
    },
    cause: 'Pseudomonas syringae ব্যাকটেরিয়া',
    spread: 'পানি, বীজ, সরঞ্জাম',
    weather: { temperature: '১৫-২৫°C', humidity: '৮০%+', rainfall: 'মাঝারি বৃষ্টি' },
    affected_crops: ['লেবু', 'আম', 'কমলা'],
    organic_control: ['বীজ শোধন', 'নিম তেল ৫ মিলি/লিটার', 'ট্রাইকোডার্মা'],
    chemical_control: ['কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার', 'স্ট্রেপটোমাইসিন ০.৫ গ্রাম/লিটার', 'ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার'],
    prevention: ['বীজ শোধন', 'ভালো জল নিষ্কাশন', 'ফসল আবর্তন'],
    severity: 'medium',
    season: 'শীত',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'bacterial-006',
    name: 'Bacterial Blight',
    scientific_name: 'Xanthomonas axonopodis',
    local_names: { bangla: 'ব্যাকটেরিয়াল ব্লাইট', chatgaiya: 'ব্যাকটেরিয়াল ব্লাইট', english: 'Bacterial Blight' },
    type: 'bacterial',
    symptoms: {
      early: 'পাতায় হলুদ দাগ',
      late: 'পাতা শুকিয়ে যায়, ফসল কমে',
      description: 'বর্ষায় বেশি হয়'
    },
    cause: 'Xanthomonas axonopodis ব্যাকটেরিয়া',
    spread: 'পানি, বীজ, সরঞ্জাম',
    weather: { temperature: '২৫-৩০°C', humidity: '৮০%+', rainfall: 'বেশি বৃষ্টি' },
    affected_crops: ['ডালিম', 'মটরশুটি', 'সয়াবিন'],
    organic_control: ['বীজ শোধন', 'নিম তেল ৫ মিলি/লিটার', 'ট্রাইকোডার্মা'],
    chemical_control: ['কপার অক্সিক্লোরাইড ৩ গ্রাম/লিটার', 'স্ট্রেপটোমাইসিন ০.৫ গ্রাম/লিটার', 'ম্যাঙ্কোজেব ২.৫ গ্রাম/লিটার'],
    prevention: ['বীজ শোধন', 'ভালো জল নিষ্কাশন', 'ফসল আবর্তন'],
    severity: 'medium',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  }
];
