export default [
  {
    id: 'pest-001',
    name: 'Aphid Damage',
    scientific_name: 'Aphis gossypii',
    local_names: { bangla: 'মাছি ক্ষতি', chatgaiya: 'মাছি ক্ষতি', english: 'Aphid Damage' },
    type: 'pest',
    symptoms: {
      early: 'পাতা কুঁকড়ে যায়',
      late: 'পাতা শুকিয়ে যায়, গাছ ধীরে বৃদ্ধি পায়',
      description: 'মাছি পানি চুষে খায়'
    },
    cause: 'Aphis gossypii পোকা',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '২০-৩০°C', humidity: '৬০-৮০%', rainfall: 'কম' },
    affected_crops: ['মরিচ', 'টমেটো', 'শসা'],
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'প্রাকৃতিক শিকারি পোকা', 'লেসিথিন ২ মিলি/লিটার'],
    chemical_control: ['দাইমিথোয়েট ০.৫ মিলি/লিটার', 'মালাথিয়ন ২ মিলি/লিটার', 'ইমিডাক্লোপ্রিড ০.৩ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'প্রাকৃতিক শিকারি পোকা সংরক্ষণ', 'সুস্থ গাছ রাখা'],
    severity: 'medium',
    season: 'শীত-গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-002',
    name: 'Whitefly Damage',
    scientific_name: 'Bemisia tabaci',
    local_names: { bangla: 'সাদা মাছি ক্ষতি', chatgaiya: 'সাদা মাছি ক্ষতি', english: 'Whitefly Damage' },
    type: 'pest',
    symptoms: {
      early: 'পাতার নিচে সাদা মাছি',
      late: 'পাতা হলুদ হয়ে যায়, ভাইরাস ছড়ায়',
      description: 'সাদা মাছি পানি চুষে খায়'
    },
    cause: 'Bemisia tabaci পোকা',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৬০-৮০%', rainfall: 'কম' },
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন'],
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'ইয়েলো স্টিকি ট্র্যাপ', 'প্রাকৃতিক শিকারি পোকা'],
    chemical_control: ['দাইমিথোয়েট ০.৫ মিলি/লিটার', 'ইমিডাক্লোপ্রিড ০.৩ মিলি/লিটার', 'নিম তেল ৫ মিলি/লিটার'],
    prevention: ['ইয়েলো স্টিকি ট্র্যাপ ব্যবহার', 'প্রাকৃতিক শিকারি পোকা সংরক্ষণ', 'নিয়মিত পর্যবেক্ষণ'],
    severity: 'high',
    season: 'গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-003',
    name: 'Thrips Damage',
    scientific_name: 'Thrips tabaci',
    local_names: { bangla: 'থ্রিপস ক্ষতি', chatgaiya: 'থ্রিপস ক্ষতি', english: 'Thrips Damage' },
    type: 'pest',
    symptoms: {
      early: 'পাতা রূপালী হয়',
      late: 'পাতা শুকিয়ে যায়',
      description: 'থ্রিপস পানি চুষে খায়'
    },
    cause: 'Thrips tabaci পোকা',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৬০-৮০%', rainfall: 'কম' },
    affected_crops: ['পেঁয়াজ', 'ধান', 'সবজি'],
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'নীল স্টিকি ট্র্যাপ', 'প্রাকৃতিক শিকারি পোকা'],
    chemical_control: ['দাইমিথোয়েট ০.৫ মিলি/লিটার', 'মালাথিয়ন ২ মিলি/লিটার', 'নিম তেল ৫ মিলি/লিটার'],
    prevention: ['নীল স্টিকি ট্র্যাপ ব্যবহার', 'প্রাকৃতিক শিকারি পোকা সংরক্ষণ', 'নিয়মিত পর্যবেক্ষণ'],
    severity: 'medium',
    season: 'গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-004',
    name: 'Borer Damage',
    scientific_name: 'Scirpophaga incertulas',
    local_names: { bangla: 'বোরার ক্ষতি', chatgaiya: 'বোরার ক্ষতি', english: 'Borer Damage' },
    type: 'pest',
    symptoms: {
      early: 'মাথার পাতা শুকিয়ে যায়',
      late: 'কাণ্ড ভেতর থেকে খেয়ে ফেলে',
      description: 'বোরার ভেতর থেকে খায়'
    },
    cause: 'Scirpophaga incertulas পোকা',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৮০%+', rainfall: 'বেশি' },
    affected_crops: ['ধান', 'মকা', 'গম'],
    organic_control: ['ট্রাইকোগ্রামা ডিম ৫০,০০০/হেক্টর', 'নিম তেল ৫ মিলি/লিটার', 'ফেরোমোন ট্র্যাপ'],
    chemical_control: ['কারবোরিল ২ গ্রাম/লিটার', 'মালাথিয়ন ২ মিলি/লিটার', 'ক্লোরপাইরিফস ১.৫ মিলি/লিটার'],
    prevention: ['ট্রাইকোগ্রামা ডিম ব্যবহার', 'ফেরোমোন ট্র্যাপ', 'সঠিক সময়ে বীজ প্রয়োগ'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-005',
    name: 'Caterpillar Damage',
    scientific_name: 'Spodoptera litura',
    local_names: { bangla: 'পোকা ক্ষতি', chatgaiya: 'পোকা ক্ষতি', english: 'Caterpillar Damage' },
    type: 'pest',
    symptoms: {
      early: 'পাতায় ছোট ছিদ্র',
      late: 'পাতা সম্পূর্ণ খেয়ে ফেলে',
      description: 'পোকা পাতা খেয়ে ফেলে'
    },
    cause: 'Spodoptera litura পোকা',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৮০%+', rainfall: 'বেশি' },
    affected_crops: ['ধান', 'পাট', 'সবজি'],
    organic_control: ['Bt ২ গ্রাম/লিটার', 'নিম তেল ৫ মিলি/লিটার', 'প্রাকৃতিক শিকারি পোকা'],
    chemical_control: ['কারবোরিল ২ গ্রাম/লিটার', 'মালাথিয়ন ২ মিলি/লিটার', 'ক্লোরপাইরিফস ১.৫ মিলি/লিটার'],
    prevention: ['Bt ব্যবহার', 'প্রাকৃতিক শিকারি পোকা সংরক্ষণ', 'নিয়মিত পর্যবেক্ষণ'],
    severity: 'high',
    season: 'বর্ষা',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-006',
    name: 'Fruit Fly Damage',
    scientific_name: 'Bactrocera dorsalis',
    local_names: { bangla: 'ফল মাছি ক্ষতি', chatgaiya: 'ফল মাছি ক্ষতি', english: 'Fruit Fly Damage' },
    type: 'pest',
    symptoms: {
      early: 'ফলে ছোট ছিদ্র',
      late: 'ফল পচে যায়',
      description: 'ফল মাছি ফলের ভেতরে ডিম দেয়'
    },
    cause: 'Bactrocera dorsalis পোকা',
    spread: 'বাতাস, স্পর্শ',
    weather: { temperature: '২৫-৩৫°C', humidity: '৬০-৮০%', rainfall: 'কম' },
    affected_crops: ['আম', 'পেপে', 'লেবু'],
    organic_control: ['মিথাইল ইউজোনল ট্র্যাপ', 'নিম তেল ৫ মিলি/লিটার', 'প্রাকৃতিক শিকারি পোকা'],
    chemical_control: ['মালাথিয়ন ২ মিলি/লিটার', 'দাইমিথোয়েট ০.৫ মিলি/লিটার', 'নিম তেল ৫ মিলি/লিটার'],
    prevention: ['মিথাইল ইউজোনল ট্র্যাপ', 'পোড়া ফল সরিয়ে ফেলা', 'নিয়মিত পর্যবেক্ষণ'],
    severity: 'high',
    season: 'গ্রীষ্ম',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-007',
    name: 'Nematode Damage',
    scientific_name: 'Meloidogyne incognita',
    local_names: { bangla: 'নেমাটোড ক্ষতি', chatgaiya: 'নেমাটোড ক্ষতি', english: 'Nematode Damage' },
    type: 'pest',
    symptoms: {
      early: 'মূলে ফোঁড়া',
      late: 'গাছ ধীরে বৃদ্ধি পায়, মরে যায়',
      description: 'নেমাটোড মূলে আক্রমণ করে'
    },
    cause: 'Meloidogyne incognita পোকা',
    spread: 'মাটি, পানি, সরঞ্জাম',
    weather: { temperature: '২৫-৩৫°C', humidity: '৮০%+', rainfall: 'বেশি' },
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন'],
    organic_control: ['নিম খিল ২০ কেজি/হেক্টর', 'ট্রাইকোডার্মা ১০ গ্রাম/কেজি মাটি', 'লেগিউম ফসল আবর্তন'],
    chemical_control: ['কারবোফুরান ১০ গ্রাম/কেজি মাটি', 'অক্সামিল ৫ গ্রাম/কেজি মাটি', 'নিম খিল ২০ কেজি/হেক্টর'],
    prevention: ['লেগিউম ফসল আবর্তন', 'নিম খিল ব্যবহার', 'সুস্থ বীজ ব্যবহার'],
    severity: 'high',
    season: 'সর্বকালীন',
    source: 'BARI',
    url: 'https://bari.gov.bd'
  }
];
