module.exports = [
  {
    id: 'chem-001',
    name: 'Urea',
    scientific_name: 'CO(NH2)2',
    local_names: { bangla: 'ইউরিয়া', chatgaiya: 'ইউরিয়াডা', english: 'Urea' },
    type: 'chemical',
    category: 'nitrogen',
    composition: '৪৬% নাইট্রোজেন',
    npk: { n: 46, p: 0, k: 0 },
    micronutrients: [],
    usage: { method: 'মাটিতে প্রয়োগ বা পাতায় স্প্রে', timing: 'বৃদ্ধির সময়', frequency: 'প্রতি ১৫-২০ দিন' },
    dosage: { field: '১০০-১২০ কেজি/একর', garden: '২০-৩০ গ্রাম/গাছ', spray: '২% দ্রবণ (২০ গ্রাম/লিটার)' },
    advantages: ['দ্রুত নাইট্রোজেন সরবরাহ', 'সাশ্রয়ী মূল্য', 'সহজে পাওয়া যায়'],
    disadvantages: ['অতিরিক্ত ব্যবহারে ক্ষতিকর', 'গ্যাস হারিয়ে যায়', 'মাটির অম্লতা বাড়ায়'],
    recommended_crops: ['ধান', 'গম', 'ভেজি', 'পাতা শাক', 'বাগানের শাক'],
    safety: ['ভেজা মাটিতে দিন', 'শুকনো মাটিতে দিলে গ্যাস হারায়', 'পাতায় স্প্রে করার পর পানি দিন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-002',
    name: 'DAP (Di-Ammonium Phosphate)',
    scientific_name: '(NH4)2HPO4',
    local_names: { bangla: 'ডিএপি', chatgaiya: 'ডিএপিয়া', english: 'DAP' },
    type: 'chemical',
    category: 'phosphorus',
    composition: '১৮% নাইট্রোজেন, ৪৬% ফসফরাস',
    npk: { n: 18, p: 46, k: 0 },
    micronutrients: [],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের সময়', frequency: 'একবার' },
    dosage: { field: '৫০-৬০ কেজি/একর', garden: '১৫-২০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['মূল গঠনে সাহায্য করে', 'ফসলের শেষ পর্যায়ে কার্যকর', 'দ্রুত মিশে যায়'],
    disadvantages: ['অতিরিক্ত ব্যবহারে ফসফরাস জমে যায়', 'মাটির pH কমায়', 'সাশ্রয়ী নয়'],
    recommended_crops: ['ধান', 'গম', 'পেঁপে', 'আলু', 'মিষ্টি আলু'],
    safety: ['মাটিতে মিশিয়ে দিন', 'চোখে লাগানো যাবে না', 'শিশুদের নাগালের বাইরে রাখুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-003',
    name: 'TSP (Triple Super Phosphate)',
    scientific_name: 'Ca(H2PO4)2',
    local_names: { bangla: 'টিএসপি', chatgaiya: 'টিএসপিয়া', english: 'TSP' },
    type: 'chemical',
    category: 'phosphorus',
    composition: '৪৬% ফসফরাস (P2O5)',
    npk: { n: 0, p: 46, k: 0 },
    micronutrients: ['ক্যালসিয়াম'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের সময়', frequency: 'একবার' },
    dosage: { field: '৪০-৫০ কেজি/একর', garden: '১০-১৫ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['মূল গঠনে সাহায্য করে', 'ক্যালসিয়াম সরবরাহ করে', 'ফসলের মান বাড়ায়'],
    disadvantages: ['দ্রুত মিশে না যাওয়া', 'অতিরিক্ত ব্যবহারে মাটিতে জমে যায়', 'সাশ্রয়ী নয়'],
    recommended_crops: ['ধান', 'গম', 'তরমুজ', 'বীজবপনের ফসল'],
    safety: ['মাটিতে মিশিয়ে দিন', 'ধুলোবালি এড়িয়ে চলুন', 'মাস্ক পরে ব্যবহার করুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-004',
    name: 'MOP (Muriate of Potash)',
    scientific_name: 'KCl',
    local_names: { bangla: 'এমওপি', chatgaiya: 'মুরিয়েট', english: 'MOP' },
    type: 'chemical',
    category: 'potassium',
    composition: '৬০% পটাশিয়াম (K2O)',
    npk: { n: 0, p: 0, k: 60 },
    micronutrients: [],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'ফুল ও ফল ধরার সময়', frequency: '১-২ বার' },
    dosage: { field: '৩০-৪০ কেজি/একর', garden: '১০-১৫ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['ফলের মান বাড়ায়', 'রোগ প্রতিরোধ ক্ষমতা বাড়ায়', 'পানি শোষণে সাহায্য করে'],
    disadvantages: ['অতিরিক্ত ব্যবহারে লবণাক্ততা বাড়ায়', 'শুকনো মাটিতে ক্ষতিকর', 'দামি'],
    recommended_crops: ['আলু', 'পেঁপে', 'কলা', 'আম', 'মরিচ'],
    safety: ['ভেজা মাটিতে দিন', 'লবণাক্ত মাটিতে ব্যবহার করবেন না', 'মাটির পরীক্ষা করে ব্যবহার করুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-005',
    name: 'Gypsum',
    scientific_name: 'CaSO4·2H2O',
    local_names: { bangla: 'জিপসাম', chatgaiya: 'জিপসাম', english: 'Gypsum' },
    type: 'chemical',
    category: 'calcium',
    composition: '২৩% ক্যালসিয়াম, ১৮% সালফার',
    npk: { n: 0, p: 0, k: 0 },
    micronutrients: ['ক্যালসিয়াম', 'সালফার'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'বীজ বপনের আগে', frequency: 'একবার' },
    dosage: { field: '২০০-৩০০ কেজি/একর', garden: '৫০-১০০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['মাটির কঠিনতা কমায়', 'সোডিয়াম নিষ্কাশন করে', 'ক্যালসিয়াম সরবরাহ করে'],
    disadvantages: ['দ্রুত কাজ করে না', 'অতিরিক্ত ব্যবহারে pH বাড়ায়', 'কয়েক বছর লাগে'],
    recommended_crops: ['ধান', 'গম', 'সবজি', 'ফল'],
    safety: ['মাটির পরীক্ষা করে ব্যবহার করুন', 'ধুলোবালি এড়িয়ে চলুন', 'শুকনো মাটিতে ব্যবহার করবেন না'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-006',
    name: 'Magnesium Sulphate',
    scientific_name: 'MgSO4·7H2O',
    local_names: { bangla: 'ম্যাগনেশিয়াম সালফেট', chatgaiya: 'এপসম সল্ট', english: 'Epsom Salt' },
    type: 'chemical',
    category: 'micronutrient',
    composition: '১৩% ম্যাগনেশিয়াম, ১৬% সালফার',
    npk: { n: 0, p: 0, k: 0 },
    micronutrients: ['ম্যাগনেশিয়াম', 'সালফার'],
    usage: { method: 'পাতায় স্প্রে বা মাটিতে প্রয়োগ', timing: 'পাতা হলুদ হলে', frequency: 'প্রতি ১৫-২০ দিন' },
    dosage: { field: '১০-১৫ কেজি/একর', garden: '৫-১০ গ্রাম/গাছ', spray: '২% দ্রবণ (২০ গ্রাম/লিটার)' },
    advantages: ['ক্লোরোফিল উৎপাদনে সাহায্য করে', 'ফসলের মান বাড়ায়', 'দ্রুত শোষিত হয়'],
    disadvantages: ['অতিরিক্ত ব্যবহারে ম্যাগনেশিয়াম বিষাক্ততা', 'পানিতে দ্রুত মিশে যায়', 'কার্যকর নয়'],
    recommended_crops: ['টমেটো', 'মরিচ', 'আলু', 'গম', 'ভেজি'],
    safety: ['পাতায় স্প্রে করার পর পানি দিন', 'চোখে লাগানো যাবে না', 'শিশুদের নাগালের বাইরে রাখুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-007',
    name: 'Boric Acid',
    scientific_name: 'H3BO3',
    local_names: { bangla: 'বোরিক এসিড', chatgaiya: 'বোরিক', english: 'Boric Acid' },
    type: 'chemical',
    category: 'micronutrient',
    composition: '১৭% বোরন',
    npk: { n: 0, p: 0, k: 0 },
    micronutrients: ['বোরন'],
    usage: { method: 'পাতায় স্প্রে বা মাটিতে প্রয়োগ', timing: 'ফুল ও ফল ধরার সময়', frequency: '২-৩ বার' },
    dosage: { field: '২-৩ কেজি/একর', garden: '২-৩ গ্রাম/গাছ', spray: '০.২% দ্রবণ (২ গ্রাম/লিটার)' },
    advantages: ['ফুল ও ফল ধরতে সাহায্য করে', 'বীজ উৎপাদনে সাহায্য করে', 'মাটির উর্বরতা বাড়ায়'],
    disadvantages: ['অতিরিক্ত ব্যবহারে বিষাক্ত', 'সঠিক মাত্রা না জানলে ক্ষতিকর', 'দ্রুত কাজ করে না'],
    recommended_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'ফুলকপি', 'ক্যাপসিকাম'],
    safety: ['সঠিক মাত্রায় ব্যবহার করুন', 'চোখে লাগানো যাবে না', 'মাস্ক পরে ব্যবহার করুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-008',
    name: 'Zinc Sulphate',
    scientific_name: 'ZnSO4·7H2O',
    local_names: { bangla: 'জিংক সালফেট', chatgaiya: 'জিংক', english: 'Zinc Sulphate' },
    type: 'chemical',
    category: 'micronutrient',
    composition: '৩৩% জিংক',
    npk: { n: 0, p: 0, k: 0 },
    micronutrients: ['জিংক'],
    usage: { method: 'পাতায় স্প্রে বা মাটিতে প্রয়োগ', timing: 'বৃদ্ধির সময়', frequency: '২-৩ বার' },
    dosage: { field: '১০-১৫ কেজি/একর', garden: '৫-১০ গ্রাম/গাছ', spray: '০.৫% দ্রবণ (৫ গ্রাম/লিটার)' },
    advantages: ['এনজাইমের কার্যকলাপে সাহায্য করে', 'ফসলের পরিমাণ বাড়ায়', 'রোগ প্রতিরোধ ক্ষমতা বাড়ায়'],
    disadvantages: ['অতিরিক্ত ব্যবহারে বিষাক্ত', 'মাটির pH প্রভাবিত করে', 'সঠিক মাত্রা না জানলে ক্ষতিকর'],
    recommended_crops: ['ধান', 'গম', 'ভেজি', 'টমেটো', 'আলু'],
    safety: ['সঠিক মাত্রায় ব্যবহার করুন', 'চোখে লাগানো যাবে না', 'শিশুদের নাগালের বাইরে রাখুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-009',
    name: 'Ferrous Sulphate',
    scientific_name: 'FeSO4·7H2O',
    local_names: { bangla: 'ফেরাস সালফেট', chatgaiya: 'লোহার লবণ', english: 'Iron Sulphate' },
    type: 'chemical',
    category: 'micronutrient',
    composition: '২০% লোহা',
    npk: { n: 0, p: 0, k: 0 },
    micronutrients: ['লোহা'],
    usage: { method: 'পাতায় স্প্রে বা মাটিতে প্রয়োগ', timing: 'পাতা হলুদ হলে', frequency: 'প্রতি ১৫-২০ দিন' },
    dosage: { field: '৫-১০ কেজি/একর', garden: '৫-১০ গ্রাম/গাছ', spray: '০.৫% দ্রবণ (৫ গ্রাম/লিটার)' },
    advantages: ['ক্লোরোফিল উৎপাদনে সাহায্য করে', 'পাতার রঙ উজ্জ্বল করে', 'দ্রুত শোষিত হয়'],
    disadvantages: ['অতিরিক্ত ব্যবহারে বিষাক্ত', 'মাটির pH কমায়', 'কার্যকর নয়'],
    recommended_crops: ['ধান', 'গম', 'ভেজি', 'টমেটো', 'আলু'],
    safety: ['পাতায় স্প্রে করার পর পানি দিন', 'চোখে লাগানো যাবে না', 'মাস্ক পরে ব্যবহার করুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-010',
    name: 'Calcium Ammonium Nitrate',
    scientific_name: 'Ca(NO3)2 + NH4NO3',
    local_names: { bangla: 'ক্যালসিয়াম অ্যামোনিয়াম নাইট্রেট', chatgaiya: 'সিএএন', english: 'CAN' },
    type: 'chemical',
    category: 'nitrogen',
    composition: '২৭% নাইট্রোজেন, ২০% ক্যালসিয়াম',
    npk: { n: 27, p: 0, k: 0 },
    micronutrients: ['ক্যালসিয়াম'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'বৃদ্ধির সময়', frequency: 'প্রতি ২০-২৫ দিন' },
    dosage: { field: '৮০-১০০ কেজি/একর', garden: '২০-৩০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['ইউরিয়ার তুলনায় কম গ্যাস হারায়', 'ক্যালসিয়াম সরবরাহ করে', 'মাটির pH সমতুল্য রাখে'],
    disadvantages: ['ইউরিয়ার তুলনায় দামি', 'শুকনো মাটিতে কম কার্যকর', 'সহজে পাওয়া যায় না'],
    recommended_crops: ['ধান', 'গম', 'ভেজি', 'পাতা শাক'],
    safety: ['ভেজা মাটিতে দিন', 'শুকনো মাটিতে দিলে কম কার্যকর', 'পাতায় স্প্রে করার পর পানি দিন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-011',
    name: 'Ammonium Sulphate',
    scientific_name: '(NH4)2SO4',
    local_names: { bangla: 'অ্যামোনিয়াম সালফেট', chatgaiya: 'সালফেট', english: 'Ammonium Sulphate' },
    type: 'chemical',
    category: 'nitrogen',
    composition: '২১% নাইট্রোজেন, ২৪% সালফার',
    npk: { n: 21, p: 0, k: 0 },
    micronutrients: ['সালফার'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'বৃদ্ধির সময়', frequency: 'প্রতি ১৫-২০ দিন' },
    dosage: { field: '৮০-১০০ কেজি/একর', garden: '২০-৩০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['ইউরিয়ার তুলনায় কম গ্যাস হারায়', 'সালফার সরবরাহ করে', 'মাটির অম্লতা বাড়ায়'],
    disadvantages: ['ইউরিয়ার তুলনায় কম নাইট্রোজেন', 'মাটির অম্লতা বাড়ায়', 'দামি'],
    recommended_crops: ['ধান', 'গম', 'ভেজি', 'পাতা শাক'],
    safety: ['ভেজা মাটিতে দিন', 'শুকনো মাটিতে দিলে কম কার্যকর', 'পাতায় স্প্রে করার পর পানি দিন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'chem-012',
    name: 'Single Super Phosphate',
    scientific_name: 'Ca(H2PO4)2 + CaSO4',
    local_names: { bangla: 'এসএসপি', chatgaiya: 'সুপার ফসফেট', english: 'SSP' },
    type: 'chemical',
    category: 'phosphorus',
    composition: '১৬% ফসফরাস (P2O5), ১২% সালফার, ২০% ক্যালসিয়াম',
    npk: { n: 0, p: 16, k: 0 },
    micronutrients: ['ক্যালসিয়াম', 'সালফার'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের সময়', frequency: 'একবার' },
    dosage: { field: '১০০-১৫০ কেজি/একর', garden: '৩০-৫০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['সাশ্রয়ী মূল্য', 'ক্যালসিয়াম ও সালফার সরবরাহ করে', 'মাটির গঠন উন্নত করে'],
    disadvantages: ['ফসফরাসের পরিমাণ কম', 'দ্রুত মিশে না যাওয়া', 'অতিরিক্ত ব্যবহারে মাটিতে জমে যায়'],
    recommended_crops: ['ধান', 'গম', 'আলু', 'পেঁপে', 'মিষ্টি আলু'],
    safety: ['মাটিতে মিশিয়ে দিন', 'ধুলোবালি এড়িয়ে চলুন', 'মাস্ক পরে ব্যবহার করুন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  }
];