module.exports = [
  {
    id: 'org-001',
    name: 'Compost',
    scientific_name: 'Organic Matter Decomposed',
    local_names: { bangla: 'খাদ্য খাদ', chatgaiya: 'খাদ মাটি', english: 'Compost' },
    type: 'organic',
    category: 'organic_manure',
    composition: '১.৫-২% নাইট্রোজেন, ০.৫-১% ফসফরাস, ০.৫-১% পটাশিয়াম',
    npk: { n: 2, p: 1, k: 1 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম', 'সালফার', 'জিংক', 'লোহা'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের ১৫-২০ দিন আগে', frequency: 'প্রতি মৌসুম' },
    dosage: { field: '২-৩ টন/একর', garden: '১-২ কেজি/গাছ', spray: 'N/A' },
    advantages: ['মাটির গঠন উন্নত করে', 'পানি ধরে রাখে', 'মাইক্রোবিয়াল কার্যকলাপ বাড়ায়'],
    disadvantages: ['তৈরিতে সময় লাগে', 'ফসফরাস ও পটাশিয়াম কম', 'নিয়মিত প্রয়োজন'],
    recommended_crops: ['সব ধরনের ফসল', 'শাকসবজি', 'ফল গাছ'],
    safety: ['পুরোপুরি গলে গেলে ব্যবহার করুন', 'কাঁচি খাদ ব্যবহার করবেন না', 'মাটিতে মিশিয়ে দিন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'org-002',
    name: 'Vermicompost',
    scientific_name: 'Earthworm Castings',
    local_names: { bangla: 'কৃমি খাদ', chatgaiya: 'কৃমি খাদ মাটি', english: 'Vermicompost' },
    type: 'organic',
    category: 'organic_manure',
    composition: '২-৩% নাইট্রোজেন, ১-১.৫% ফসফরাস, ১-১.৫% পটাশিয়াম',
    npk: { n: 3, p: 1.5, k: 1.5 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম', 'সালফার', 'জিংক', 'লোহা', 'বোরন'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের ১৫-২০ দিন আগে', frequency: 'প্রতি মৌসুম' },
    dosage: { field: '১.৫-২ টন/একর', garden: '০.৫-১ কেজি/গাছ', spray: 'N/A' },
    advantages: ['রাসায়নিক সারের তুলনায় বেশি উর্বর', 'মাইক্রোবিয়াল কার্যকলাপ বাড়ায়', 'পানি ধরে রাখে'],
    disadvantages: ['তৈরিতে সময় লাগে', 'ফসফরাস ও পটাশিয়াম কম', 'নিয়মিত প্রয়োজন'],
    recommended_crops: ['সব ধরনের ফসল', 'শাকসবজি', 'ফল গাছ', 'ফুল'],
    safety: ['পুরোপুরি গলে গেলে ব্যবহার করুন', 'কাঁচি খাদ ব্যবহার করবেন না', 'মাটিতে মিশিয়ে দিন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'org-003',
    name: 'Cow Dung',
    scientific_name: 'Bos taurus Excreta',
    local_names: { bangla: 'গোবর', chatgaiya: 'গোবর খাদ', english: 'Cow Dung' },
    type: 'organic',
    category: 'animal_manure',
    composition: '০.৫% নাইট্রোজেন, ০.২% ফসফরাস, ০.৫% পটাশিয়াম',
    npk: { n: 0.5, p: 0.2, k: 0.5 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের ১৫-২০ দিন আগে', frequency: 'প্রতি মৌসুম' },
    dosage: { field: '৫-১০ টন/একর', garden: '২-৩ কেজি/গাছ', spray: 'N/A' },
    advantages: ['সুলভ মূল্যে পাওয়া যায়', 'মাটির গঠন উন্নত করে', 'পানি ধরে রাখে'],
    disadvantages: ['রাসায়নিক সারের তুলনায় কম শক্তিশালী', 'পোকামাকড় আকর্ষণ করতে পারে', 'গলে গেলে ভালো'],
    recommended_crops: ['সব ধরনের ফসল', 'শাকসবজি', 'ফল গাছ'],
    safety: ['পুরোপুরি গলে গেলে ব্যবহার করুন', 'কাঁচি গোবর ব্যবহার করবেন না', 'মাটিতে মিশিয়ে দিন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'org-004',
    name: 'Neem Cake',
    scientific_name: 'Azadirachta indica Cake',
    local_names: { bangla: 'নিম খাদ', chatgaiya: 'নিম খাদ', english: 'Neem Cake' },
    type: 'organic',
    category: 'plant_based',
    composition: '৫-৬% নাইট্রোজেন, ১-২% ফসফরাস, ১-২% পটাশিয়াম',
    npk: { n: 5, p: 1.5, k: 1.5 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম', 'সালফার'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের সময়', frequency: 'একবার' },
    dosage: { field: '২০০-৩০০ কেজি/একর', garden: '৫০-১০০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['পোকামাকড় প্রতিরোধ করে', 'নাইট্রোজেন সরবরাহ করে', 'মাটির উর্বরতা বাড়ায়'],
    disadvantages: ['দামি', 'কম পাওয়া যায়', 'সঠিক মাত্রা না জানলে ক্ষতিকর'],
    recommended_crops: ['সব ধরনের ফসল', 'শাকসবজি', 'ফল গাছ'],
    safety: ['সঠিক মাত্রায় ব্যবহার করুন', 'চোখে লাগানো যাবে না', 'শিশুদের নাগালের বাইরে রাখুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'org-005',
    name: 'Bone Meal',
    scientific_name: 'Ground Animal Bones',
    local_names: { bangla: 'হাড়ের গুঁড়া', chatgaiya: 'হাড় খাদ', english: 'Bone Meal' },
    type: 'organic',
    category: 'animal_based',
    composition: '৪% নাইট্রোজেন, ১২-১৬% ফসফরাস, ০% পটাশিয়াম',
    npk: { n: 4, p: 14, k: 0 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের সময়', frequency: 'একবার' },
    dosage: { field: '১০০-২০০ কেজি/একর', garden: '৩০-৫০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['ফসফরাস সরবরাহ করে', 'দীর্ঘস্থায়ী কার্যকর', 'মূল গঠনে সাহায্য করে'],
    disadvantages: ['দ্রুত কাজ করে না', 'পটাশিয়াম কম', 'দামি'],
    recommended_crops: ['ফুল', 'ফল গাছ', 'আলু', 'পেঁপে'],
    safety: ['মাটিতে মিশিয়ে দিন', 'কুকুরের নাগালের বাইরে রাখুন', 'শুকনো মাটিতে ব্যবহার করবেন না'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'org-006',
    name: 'Fish Meal',
    scientific_name: 'Ground Fish Waste',
    local_names: { bangla: 'মাছের খাদ', chatgaiya: 'মাছ খাদ', english: 'Fish Meal' },
    type: 'organic',
    category: 'animal_based',
    composition: '৮-১০% নাইট্রোজেন, ৪-৬% ফসফরাস, ২-৩% পটাশিয়াম',
    npk: { n: 9, p: 5, k: 2.5 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম', 'সালফার'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের সময়', frequency: 'একবার' },
    dosage: { field: '১০০-১৫০ কেজি/একর', garden: '৩০-৫০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['NPK সরবরাহ করে', 'দ্রুত কাজ করে', 'মাটির উর্বরতা বাড়ায়'],
    disadvantages: ['গন্ধ তৈরি করে', 'পোকামাকড় আকর্ষণ করতে পারে', 'দামি'],
    recommended_crops: ['সব ধরনের ফসল', 'শাকসবজি', 'ফল গাছ'],
    safety: ['মাটিতে মিশিয়ে দিন', 'শুকনো জায়গায় রাখুন', 'পোকামাকড় এড়িয়ে চলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'org-007',
    name: 'Mustard Cake',
    scientific_name: 'Brassica campestris Cake',
    local_names: { bangla: 'সরিষার খাদ', chatgaiya: 'সরিষা খাদ', english: 'Mustard Cake' },
    type: 'organic',
    category: 'plant_based',
    composition: '৫-৬% নাইট্রোজেন, ২-৩% ফসফরাস, ১-২% পটাশিয়াম',
    npk: { n: 5.5, p: 2.5, k: 1.5 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম', 'সালফার'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের সময়', frequency: 'একবার' },
    dosage: { field: '২০০-৩০০ কেজি/একর', garden: '৫০-১০০ গ্রাম/গাছ', spray: 'N/A' },
    advantages: ['NPK সরবরাহ করে', 'পোকামাকড় প্রতিরোধ করে', 'মাটির উর্বরতা বাড়ায়'],
    disadvantages: ['দামি', 'কম পাওয়া যায়', 'সঠিক মাত্রা না জানলে ক্ষতিকর'],
    recommended_crops: ['সব ধরনের ফসল', 'শাকসবজি', 'ফল গাছ'],
    safety: ['সঠিক মাত্রায় ব্যবহার করুন', 'চোখে লাগানো যাবে না', 'শিশুদের নাগালের বাইরে রাখুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'org-008',
    name: 'Green Manure',
    scientific_name: 'Sesbania/Crotalaria',
    local_names: { bangla: 'সবুজ সার', chatgaiya: 'হরিত খাদ', english: 'Green Manure' },
    type: 'organic',
    category: 'plant_based',
    composition: '০.৫-১% নাইট্রোজেন, ০.১-০.২% ফসফরাস, ০.৩-০.৫% পটাশিয়াম',
    npk: { n: 0.75, p: 0.15, k: 0.4 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম'],
    usage: { method: 'মাটিতে মিশিয়ে দিন', timing: 'ফুল ফোটার আগে', frequency: 'একবার' },
    dosage: { field: '২-৩ টন/একর', garden: '১-২ কেজি/গাছ', spray: 'N/A' },
    advantages: ['মাটির নাইট্রোজেন বাড়ায়', 'মাটির গঠন উন্নত করে', 'পানি ধরে রাখে'],
    disadvantages: ['নাইট্রোজেন কম', 'সময় লাগে', 'নিয়মিত প্রয়োজন'],
    recommended_crops: ['ধান', 'গম', 'ভেজি'],
    safety: ['ফুল ফোটার আগে মাটিতে মিশিয়ে দিন', 'কাঁচি অবস্থায় মিশিয়ে দিন', 'পানি দিন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  },
  {
    id: 'org-009',
    name: 'Poultry Litter',
    scientific_name: 'Chicken Excreta + Bedding',
    local_names: { bangla: 'মুরগির খাদ', chatgaiya: 'মুরগি খাদ', english: 'Poultry Litter' },
    type: 'organic',
    category: 'animal_manure',
    composition: '৩-৪% নাইট্রোজেন, ২-৩% ফসফরাস, ২-৩% পটাশিয়াম',
    npk: { n: 3.5, p: 2.5, k: 2.5 },
    micronutrients: ['ক্যালসিয়াম', 'ম্যাগনেশিয়াম', 'সালফার'],
    usage: { method: 'মাটিতে প্রয়োগ', timing: 'রোপণের ১৫-২০ দিন আগে', frequency: 'প্রতি মৌসুম' },
    dosage: { field: '১-২ টন/একর', garden: '০.৫-১ কেজি/গাছ', spray: 'N/A' },
    advantages: ['NPK সরবরাহ করে', 'দ্রুত কাজ করে', 'মাটির উর্বরতা বাড়ায়'],
    disadvantages: ['গন্ধ তৈরি করে', 'পোকামাকড় আকর্ষণ করতে পারে', 'অতিরিক্ত ব্যবহারে লবণাক্ততা বাড়ায়'],
    recommended_crops: ['সব ধরনের ফসল', 'শাকসবজি', 'ফল গাছ'],
    safety: ['পুরোপুরি গলে গেলে ব্যবহার করুন', 'কাঁচি খাদ ব্যবহার করবেন না', 'মাটিতে মিশিয়ে দিন'],
    source: 'DAE',
    url: 'https://dae.gov.bd'
  }
];