export default [
  {
    id: 'pest-001',
    name: 'Golden Apple Snail',
    scientific_name: 'Pomacea canaliculata',
    local_names: { bangla: 'গোল্ডেন এপেল শামুক', chatgaiya: 'শামুক', english: 'Golden Apple Snail' },
    type: 'mollusk',
    description: 'বড় হলুদ/কমলা শামুক, ধানের চাষে বেশি ক্ষতি করে',
    damage: 'ধানের চাষা খেয়ে ফেলে, ফসলের বড় ক্ষতিকারক',
    affected_crops: ['ধান', 'সবজি', 'জলাশয়ের ফসল'],
    season: 'বর্ষাকালীন',
    organic_control: ['হাত দিয়ে সংগ্রহ', 'তেল ছিটিয়ে দিন', 'পরিষ্কার জলাশয়'],
    chemical_control: ['মেটালডিহাইড ৫ গ্রাম/লিটার', 'নিকোসালফারন ১ মিলি/লিটার'],
    prevention: ['পরিষ্কার জলাশয়', 'নিয়মিত পর্যবেক্ষণ', 'শামুক সংগ্রহ'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-002',
    name: 'Root-Knot Nematode',
    scientific_name: 'Meloidogyne spp.',
    local_names: { bangla: 'মূল গিঁট পোকা', chatgaiya: 'মূল পোকা', english: 'Root-Knot Nematode' },
    type: 'nematode',
    description: 'অতি ছোট পোকা, গাছের মূলে গিঁট তৈরি করে',
    damage: 'গাছের মূলে গিঁট তৈরি করে, পুষ্টি শোষণে বাধা দেয়, গাছ দুর্বল হয়',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'শসা', 'আলু'],
    season: 'সর্বকালীন',
    organic_control: ['নিম খাদ ব্যবহার', 'মশলা ফসল পরিবর্তন', 'সূর্যালোকে মাটি শুকান'],
    chemical_control: ['কার্বোফুরান ৫ গ্রাম/লিটার', 'অক্সামিল ১ মিলি/লিটার'],
    prevention: ['ফসল পরিবর্তন', 'নিম খাদ ব্যবহার', 'পরিষ্কার বীজ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-003',
    name: 'Cutworm',
    scientific_name: 'Agrotis ipsilon',
    local_names: { bangla: 'কাটওয়ার্ম', chatgaiya: 'মাটি পোকা', english: 'Cutworm' },
    type: 'chewing',
    description: 'বাদামি লার্ভা রাতে কান্ড কেটে ফেলে',
    damage: 'গাছের কান্ড কেটে ফেলে, গাছ পড়ে যায়',
    affected_crops: ['টমেটো', 'মরিচ', 'বেগুন', 'শসা', 'সালাদ'],
    season: 'বসন্তকালীন',
    organic_control: ['বি.টি. স্প্রে ৫ গ্রাম/লিটার', 'ফেরোমোন ট্র্যাপ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস'],
    chemical_control: ['কারবারিল ১ মিলি/লিটার', 'ফিপ্রোনিল ০.৫ মিলি/লিটার', 'এমামেক্টিন বেনজোয়েট ০.৪ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস', 'ফেরোমোন ট্র্যাপ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-004',
    name: 'Scale Insect',
    scientific_name: 'Aonidiella aurantii',
    local_names: { bangla: 'স্কেল পোকা', chatgaiya: 'স্কেল', english: 'Scale Insect' },
    type: 'sucking',
    description: 'ছোট বাদামি/সাদা পোকা, গাছের কান্ডে আটকে থাকে',
    damage: 'রস চুষে খায়, গাছ দুর্বল হয়, মধুর আস্বেক তৈরি হয়',
    affected_crops: ['কলা', 'আম', 'পেঁপে', 'সবজি', 'ফুল'],
    season: 'সর্বকালীন',
    organic_control: ['নিম তেল ৫ মিলি/লিটার', 'সাবান পানি স্প্রে', 'লেডিবার্ড ছেড়ে দিন'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার', 'থায়ামেথোক্সাম ০.৩ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'মিত্র পোকা ব্যবহার', 'আক্রান্ত অংশ কেটে ফেলুন'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-005',
    name: 'Termites',
    scientific_name: 'Odontotermes obesus',
    local_names: { bangla: 'দাঁড় পোকা', chatgaiya: 'দাঁড়', english: 'Termites' },
    type: 'chewing',
    description: 'ছোট সাদা/বাদামি পোকা, কাঠ ও মাটি খায়',
    damage: 'গাছের মূল ও কান্ড খায়, গাছ শুকিয়ে যায়',
    affected_crops: ['ধান', 'গম', 'সবজি', 'ফল গাছ'],
    season: 'বর্ষাকালীন',
    organic_control: ['নিম খাদ ব্যবহার', 'মশলা ফসল পরিবর্তন', 'সূর্যালোকে মাটি শুকান'],
    chemical_control: ['কার্বোফুরান ৫ গ্রাম/লিটার', 'অক্সামিল ১ মিলি/লিটার'],
    prevention: ['ফসল পরিবর্তন', 'নিম খাদ ব্যবহার', 'পরিষ্কার বীজ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-006',
    name: 'Red Pumpkin Beetle',
    scientific_name: 'Aulacophora foveicollis',
    local_names: { bangla: 'কুমড়া পোকা', chatgaiya: 'কুমড়া পোকা', english: 'Red Pumpkin Beetle' },
    type: 'chewing',
    description: 'লাল/কমলা পোকা, পাতা খায়',
    damage: 'পাতা খেয়ে ফেলে, ফসলের বড় ক্ষতিকারক',
    affected_crops: ['কুমড়া', 'পেঁপে', 'তরমুজ', 'মিষ্টি আলু'],
    season: 'গ্রীষ্মকালীন',
    organic_control: ['হাত দিয়ে সংগ্রহ', 'নিম তেল ৫ মিলি/লিটার', 'হলুদ স্টিকি ট্র্যাপ'],
    chemical_control: ['ডাইমিথোয়েট ১ মিলি/লিটার', 'মালাথিয়ন ০.৫ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস', 'ফেরোমোন ট্র্যাপ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-007',
    name: 'Fruit Fly',
    scientific_name: 'Bactrocera dorsalis',
    local_names: { bangla: 'ফল মাছি', chatgaiya: 'ফল মাছি', english: 'Fruit Fly' },
    type: 'dipteran',
    description: 'ছোট মাছি, ফলের ভিতরে ডিম পাড়ে',
    damage: 'ফলের ভিতরে লার্ভা খায়, ফল নষ্ট করে',
    affected_crops: ['আম', 'পেঁপে', 'কলা', 'লিচু', 'কাঁঠাল'],
    season: 'গ্রীষ্মকালীন',
    organic_control: ['মিথাইল ইউজোনোল ট্র্যাপ', 'লেডিবার্ড ছেড়ে দিন', 'আক্রান্ত ফল সংগ্রহ ও ধ্বংস'],
    chemical_control: ['মালাথিয়ন ০.৫ মিলি/লিটার', 'ডাইমিথোয়েট ১ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'আক্রান্ত ফল সংগ্রহ ও ধ্বংস', 'মিথাইল ইউজোনোল ট্র্যাপ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'pest-008',
    name: 'Armyworm',
    scientific_name: 'Spodoptera litura',
    local_names: { bangla: 'আর্মি পোকা', chatgaiya: 'আর্মি পোকা', english: 'Armyworm' },
    type: 'chewing',
    description: 'সবুজ/বাদামি লার্ভা, গুচ্ছে চলে',
    damage: 'পাতা খেয়ে ফেলে, গাছ নষ্ট করে',
    affected_crops: ['ধান', 'গম', 'ভুট্টা', 'সুজি'],
    season: 'বর্ষাকালীন',
    organic_control: ['বি.টি. স্প্রে ৫ গ্রাম/লিটার', 'ফেরোমোন ট্র্যাপ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস'],
    chemical_control: ['কারবারিল ১ মিলি/লিটার', 'ফিপ্রোনিল ০.৫ মিলি/লিটার', 'এমামেক্টিন বেনজোয়েট ০.৪ মিলি/লিটার'],
    prevention: ['নিয়মিত পর্যবেক্ষণ', 'আক্রান্ত গাছ সংগ্রহ ও ধ্বংস', 'ফেরোমোন ট্র্যাপ ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  }
];