module.exports = [
    {
        id: 'soil-001',
        title: 'মাটি পরীক্ষার গুরুত্ব',
        source: 'DAE',
        url: 'https://dae.gov.bd',
        crop: 'সর্বজনীন',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'মাটি পরীক্ষা করে সার মাত্রা নির্ধারণ করুন। DAE এর কাছে মাটি পরীক্ষার ব্যবস্থা আছে। pH ৬.০-৭.০ সবচেয়ে ভালো। জৈব পদার্থ ২-৩% থাকা উচিত।',
    },
    {
        id: 'soil-002',
        title: 'মাটির pH পরিচালনা',
        source: 'DAE',
        url: 'https://dae.gov.bd',
        crop: 'সর্বজনীন',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'মাটির pH ৬.০-৭.০ সবচেয়ে ভালো। অম্লীয় মাটিতে চুন প্রয়োগ (১-২ টন/একর)। ক্ষারীয় মাটিতে জিপসাম বা গন্ধক প্রয়োগ। প্রতি ৩ বছর পর মাটি পরীক্ষা করুন।',
    },
    {
        id: 'soil-003',
        title: 'মাটির সার সংরক্ষণ',
        source: 'DAE',
        url: 'https://dae.gov.bd',
        crop: 'সর্বজনীন',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'মাটির সার সংরক্ষণ: কমপোস্ট প্রয়োগ। ফসল আবর্তন। মিশ্র চাষ। কাভার ক্রপ। কম জোরা। কার্বনিক পদার্থ বৃদ্ধি।',
    },
    {
        id: 'soil-004',
        title: 'লবণাক্ত মাটি পরিচালনা',
        source: 'DAE',
        url: 'https://dae.gov.bd',
        crop: 'সর্বজনীন',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'লবণাক্ত মাটি পরিচালনা: জিপসাম ৩০০-৪০০ কেজি/একর। ভালো জল নিষ্কাশন। লবণাক্ততা সহনশীল জাত ব্যবহার। পলিথিন মালচিং। বৃষ্টির পানি সংরক্ষণ।',
    },
];
