import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = join(__dirname, '..', 'assets', 'js', 'app-config.js');

const recaptchaSiteKey = process.env.RECAPTCHA_SITE_KEY || '';

const content = `// Auto-generated by scripts/inject-config.js — do not edit manually
// Source: RECAPTCHA_SITE_KEY environment variable
export const RECAPTCHA_SITE_KEY = ${JSON.stringify(recaptchaSiteKey)};
`;

writeFileSync(outputPath, content, 'utf8');

console.log(`app-config.js generated — RECAPTCHA_SITE_KEY ${recaptchaSiteKey ? 'set' : 'EMPTY (App Check will not initialize)'}`);
