module.exports = [
  {
    id: 'weed-001',
    name: 'Barnyard Grass',
    scientific_name: 'Echinochloa crus-galli',
    local_names: { bangla: 'শেওড়া ঘাঁস', chatgaiya: 'শেওড়া', english: 'Barnyard Grass' },
    type: 'grass',
    description: 'দ্রুত বৃদ্ধি পায়, ধানের মতো দেখতে',
    damage: 'ধানের সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['ধান', 'গম', 'সবজি'],
    season: 'বর্ষাকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['বিউটাক্লোর ১.৫ মিলি/লিটার', 'প্রেইলিসুর-এম ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-002',
    name: 'Little Seed Ironweed',
    scientific_name: 'Vigna umbellata',
    local_names: { bangla: 'কচু পাতা', chatgaiya: 'কচু', english: 'Little Seed Ironweed' },
    type: 'broadleaf',
    description: 'ছোট সবুজ পাতা, মাটির ওপর ছড়িয়ে থাকে',
    damage: 'ধানের সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['ধান', 'সবজি'],
    season: 'বর্ষাকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['২,৪-ডি ১ মিলি/লিটার', 'মেট্রিবুজিন ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-003',
    name: 'Purple nutsedge',
    scientific_name: 'Cyperus rotundus',
    local_names: { bangla: 'হারেরা', chatgaiya: 'হারেরা', english: 'Purple Nutsedge' },
    type: 'sedge',
    description: 'তিন কোণা পাতা, কাঁদা মাটিতে বেশি হয়',
    damage: 'পুষ্টি ও পানি দখল করে, সবজিতে বেশি ক্ষতি করে',
    affected_crops: ['সবজি', 'ফল', 'আলু'],
    season: 'সর্বকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['গ্লাইফোসেট ২ মিলি/লিটার', 'অক্সাডিয়ার্জন ০.৫ মিলি/লিটার'],
    prevention: ['কাঁদা মাটি শুকিয়ে রাখুন', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-004',
    name: 'Amaranth',
    scientific_name: 'Amaranthus viridis',
    local_names: { bangla: 'বাথুয়া', chatgaiya: 'বাথুয়া', english: 'Amaranth' },
    type: 'broadleaf',
    description: 'সবুজ পাতা, দ্রুত বৃদ্ধি পায়',
    damage: 'সবজির সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['সবজি', 'ফল', 'আলু'],
    season: 'সর্বকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['২,৪-ডি ১ মিলি/লিটার', 'মেট্রিবুজিন ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-005',
    name: 'Crowfoot Grass',
    scientific_name: 'Dactyloctenium aegyptium',
    local_names: { bangla: 'মুড়ি ঘাঁস', chatgaiya: 'মুড়ি ঘাঁস', english: 'Crowfoot Grass' },
    type: 'grass',
    description: 'ছোট সবুজ ঘাঁস, মাটির ওপর ছড়িয়ে থাকে',
    damage: 'সবজির সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['সবজি', 'ফল', 'আলু'],
    season: 'গ্রীষ্মকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['গ্লাইফোসেট ২ মিলি/লিটার', 'অক্সাডিয়ার্জন ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-006',
    name: 'Spurge',
    scientific_name: 'Euphorbia hirta',
    local_names: { bangla: 'দুধ লতা', chatgaiya: 'দুধ লতা', english: 'Spurge' },
    type: 'broadleaf',
    description: 'সবুজ পাতা, দুধের মতো রস থাকে',
    damage: 'সবজির সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['সবজি', 'ফল', 'আলু'],
    season: 'সর্বকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['২,৪-ডি ১ মিলি/লিটার', 'মেট্রিবুজিন ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-007',
    name: 'Swallow Wort',
    scientific_name: 'Calotropis gigantea',
    local_names: { bangla: 'আকন্দ', chatgaiya: 'আকন্দ', english: 'Swallow Wort' },
    type: 'broadleaf',
    description: 'বড় গাছ, দুধের মতো রস থাকে',
    damage: 'ফসলের সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['সবজি', 'ফল', 'আলু'],
    season: 'সর্বকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['গ্লাইফোসেট ২ মিলি/লিটার', 'অক্সাডিয়ার্জন ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-008',
    name: 'Fimbristylis',
    scientific_name: 'Fimbristylis miliacea',
    local_names: { bangla: 'কাঁশ ঘাঁস', chatgaiya: 'কাঁশ', english: 'Fimbristylis' },
    type: 'sedge',
    description: 'তিন কোণা পাতা, কাঁদা মাটিতে বেশি হয়',
    damage: 'ধানের সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['ধান', 'সবজি'],
    season: 'বর্ষাকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['গ্লাইফোসেট ২ মিলি/লিটার', 'অক্সাডিয়ার্জন ০.৫ মিলি/লিটার'],
    prevention: ['কাঁদা মাটি শুকিয়ে রাখুন', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-009',
    name: 'Benghal Dayflower',
    scientific_name: 'Commelina benghalensis',
    local_names: { bangla: 'কচু পাতা', chatgaiya: 'কচু', english: 'Benghal Dayflower' },
    type: 'broadleaf',
    description: 'সবুজ পাতা, নীল ফুল হয়',
    damage: 'ধানের সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['ধান', 'সবজি'],
    season: 'বর্ষাকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['২,৪-ডি ১ মিলি/লিটার', 'মেট্রিবুজিন ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  },
  {
    id: 'weed-010',
    name: 'Smartweed',
    scientific_name: 'Polygonum hydropiper',
    local_names: { bangla: 'চুঁচুনি', chatgaiya: 'চুঁচুনি', english: 'Smartweed' },
    type: 'broadleaf',
    description: 'সবুজ পাতা, তীব্র গন্ধ',
    damage: 'ধানের সাথে প্রতিযোগিতা করে, পুষ্টি ও পানি দখল করে',
    affected_crops: ['ধান', 'সবজি'],
    season: 'বর্ষাকালীন',
    organic_control: ['হাত দিয়ে তুলে ফেলুন', 'মালচিং', 'পলিথিন ব্যবহার'],
    chemical_control: ['২,৪-ডি ১ মিলি/লিটার', 'মেট্রিবুজিন ০.৫ মিলি/লিটার'],
    prevention: ['পরিষ্কার বীজ ব্যবহার', 'নিয়মিত তুলে ফেলুন', 'পলিথিন ব্যবহার'],
    source: 'BARI',
    url: 'https://bari.gov.bd'
  }
];