export default [
    {
        id: 'gov-001',
        title: 'DAE সেবা',
        source: 'DAE',
        url: 'https://dae.gov.bd',
        crop: 'সর্বজনীন',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'DAE (কৃষি সম্প্রসারণ অধিদপ্তর) বাংলাদেশে কৃষি সেবা প্রদান করে। মাটি পরীক্ষা, বীজ সরবরাহ, প্রশিক্ষণ, কৃষি পরামর্শ। জেলা ও উপজেলা পর্যায়ে সেবা।',
    },
    {
        id: 'gov-002',
        title: 'BARI গবেষণা কেন্দ্র',
        source: 'BARI',
        url: 'https://bari.gov.bd',
        crop: 'সর্বজনীন',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'BARI (বাংলাদেশ কৃষি গবেষণা ইন্সটিটিউট) নতুন জাত ও প্রযুক্তি উদ্ভাবন করে। ফসল উৎপাদন, রোগ প্রতিরোধ, মাটি পরীক্ষা, কৃষি পরামর্শ।',
    },
    {
        id: 'gov-003',
        title: 'BRRI ধান গবেষণা',
        source: 'BRRI',
        url: 'https://brri.gov.bd',
        crop: 'ধান',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'BRRI (বাংলাদেশ ধান গবেষণা ইন্সটিটিউট) ধানের নতুন জাত উদ্ভাবন করে। ধান চাষের নতুন প্রযুক্তি। রোগ প্রতিরোধী জাত। উচ্চ ফলনশীল জাত।',
    },
    {
        id: 'gov-004',
        title: 'সরকারি কৃষি সাবসিডি',
        source: 'moa.gov.bd',
        url: 'https://moa.gov.bd',
        crop: 'সর্বজনীন',
        disease: null,
        season: 'সর্বকালীন',
        language: 'bangla',
        content: 'বাংলাদেশ সরকার কৃষিতে সাবসিডি প্রদান করে। সার, বীজ, যন্ত্রপাতি। ঋণ সুবিধা। বীমা। প্রশিক্ষণ। DAE এর মাধ্যমে সেবা।',
    },
];
